#!/bin/sh

# 读取环境变量 CUSTOM_DNS_SERVERS
# 格式应该是 "8.8.8.8 1.1.1.1"
DNS_SERVERS="${CUSTOM_DNS_SERVERS}"

# 检查环境变量是否被设置
if [ -n "$DNS_SERVERS" ]; then
  echo "==> Custom DNS servers detected. Configuring /etc/resolv.conf..."
  # 如果设置了，就用它来生成 /etc/resolv.conf 文件
  echo "# Generated by custom entrypoint script" > /etc/resolv.conf
  for dns in $DNS_SERVERS; do
    echo "nameserver $dns" >> /etc/resolv.conf
  done

  # 在日志中打印结果，方便调试
  echo "==> DNS configuration complete. Contents of /etc/resolv.conf:"
  cat /etc/resolv.conf
else
  # 如果没有设置环境变量，就打印警告并使用默认配置
  echo "==> Warning: CUSTOM_DNS_SERVERS not set. Using container's default DNS."
fi

echo "==> Starting Uptime Kuma server..."
# 使用 exec 来让 Uptime Kuma 进程替换掉脚本进程，这是最佳实践
# 这会执行容器原来的默认命令
exec node server/server.js
